---
name: Grott beta
version: dev
slug: grott-beta
description: The Growatt inverter monitor with current HA plugin integrated
url: https://github.com/egguy/addon-grott-beta
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services:
  - mqtt:need
init: false
map:
  - config:rw
ports:
  5279/tcp: 5279
ports_description:
  5279/tcp: The port used by grott to receive the data of the logger
options:
  data_path: /config/grott
  gmode: proxy
  grott_mqtt: false
  ginvtype: default
  ginvtypemap: ""
  retain: false
  verbose: false
  ha_plugin: true
  mqtt: {}
schema:
  gblockcmd: bool?
  gcompat: bool?
  gdecrypt: bool?
  gextension: bool?
  gextname: str?
  gextvar: str?
  ggrottip: str?
  ggrottport: port?
  ggrowattip: str?
  ggrowattport: port?
  gifbucket: str?
  gifdbname: str?
  gifip: str?
  giforg: str?
  gifpassword: password?
  gifport: port?
  giftoken: str?
  gifuser: str?
  gincludeall: bool?
  ginflux: bool?
  ginflux2: bool?
  ginverterid: str?
  ginvtype: str?
  ginvtypemap: str?
  gminrecl: int?
  gmode: str
  gmqttauth: bool?
  gmqttinverterintopic: bool?
  gmqttip: str?
  gmqttpassword: password?
  gmqttport: str?
  gmqtttopic: str?
  gmqttuser: str?
  gnoipf: bool?
  grott_mqtt: bool?
  gpvapikey: str?
  gpvdisv1: bool?
  gpvinverters: int?
  gpvoutput: bool?
  gpvsystemid: int?
  gpvtemp: bool?
  gsendbuf: bool?
  gtime: str?
  gtimezone: str?
  gvalueoffset: int?
  verbose: bool
  retain: bool
  ha_plugin: bool
  mqtt:
    host: str?
    port: int?
    user: str?
    password: str?
  data_path: str
